(define (domain capp)
    (:predicates (CUERPO ?x) (HERRAMIENTA ?x) 
        (ARMARIO ?x) (HUSILLO ?x) (DIRECCION ?x)
        (AGUJERO ?x) (RANURA ?x)
        (en ?x ?y) (vinculo ?x ?y) (pos ?r ?s))

    (:action cambio-herramienta :parameters (?h1 ?h2 ?a ?m)
        :precondition (and (HERRAMIENTA ?h1) 
        (HERRAMIENTA ?h2) (ARMARIO ?a) (HUSILLO ?m)
        (en ?h1 ?a) (en ?h2 ?m))
        :effect (and (en ?h1 ?m) (not (en ?h1 ?a)) 
        (en ?h2 ?a) (not (en ?h2 ?m))))
    
    (:action rotacion-pieza :parameters (?p ?s)
        :precondition (and (CUERPO ?p) (DIRECCION ?s) (not (en ?p ?s)))
        :effect (and (en ?p ?s)))
    
    (:action agujerear :parameters (?p ?h ?m ?a)
        :precondition (and (CUERPO ?p)
        (HERRAMIENTA ?h) (AGUJERO ?a) (HUSILLO ?m) 
        (vinculo ?h ?a)
        (not (en ?p ?a)) (en ?h ?m))
        :effect (and (en ?p ?a))
    )

    (:action fresar :parameters (?p ?h ?m ?r ?s)
        :precondition (and (CUERPO ?p) (DIRECCION ?s)
        (HERRAMIENTA ?h) (RANURA ?r) (HUSILLO ?m) 
        (vinculo ?h ?r)
        (not (en ?p ?r)) (en ?h ?m))
        :effect (and (en ?p ?r))
    )
)